---
title: "Extrapolate sinusoidal grid test report"
author: "Qu Tang"
date: '`r Sys.time()`'
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
  word_document: default
---

### Grid test input parameters
```{r, echo=FALSE, kable, warning=FALSE, result="markup"}
library(mhealthformatsupportr)
library(mhealthactivitycountsr)
library(doParallel)

if(!exists("duration")){
  duration = 5
  Fs = 40
  range = 6
  freqs = seq(1,8)
  amp = seq(8,16)
  noiseStds = 0
  phase = runif(20,min=0,max = 10)
  seed = 5
  lambda = 3
  parallel = TRUE
  interpolate = "spline_natural"
  csvResultName = "../result.csv"
  logFilename = "../result.log"
}

inputTable = data.frame("Duration" = as.character(duration),
                        "Sampling Rate" = as.character(Fs),
                        "Dynamic Range" = as.character(range),
                        "Frequencies" = paste(as.character(round(freqs, digits = 3)), collapse=","),
                        "Amplitude" = paste(as.character(round(amp, digits = 3)), collapse=","),
                        "Noise standard deviation" = paste(as.character(round(noiseStds, digits = 3)), collapse=","),
                        "Interpolate method" = interpolate,
                        "Phase" = paste(as.character(round(phase, digits = 3)), collapse=","),
                        "Random seed" = as.character(seed),
                        "Lambda" = lambda,
                        "Parallel Computing" = parallel)

inputTable = as.data.frame(t(inputTable))
names(inputTable) = "Parameter"
knitr::kable(inputTable)
```

### Grid test running time

```{r, echo=FALSE, warning = FALSE, message = FALSE, results = "asis"}

switch(Sys.info()[['sysname']],
        Windows = {logFile = logFilename},
        Linux = {logFile = logFilename},
        Darwin = {logFile = logFilename})
costTime = system.time(capture.output(result <- Extrapolate.sinusoidal.grid(duration = duration,
                                     Fs = Fs,
                                     range = range,
                                     freqs = freqs,
                                     amp = amp,
                                     noiseStds = noiseStds,
                                     phase = phase,
                                     interpolate = interpolate,
                                     seed = seed,
                                     lambda = lambda,
                                     parallel = parallel), file=logFile))
knitr::kable(as.data.frame(as.list(costTime)))
```

### Grid test result in heatmap
```{r, echo=FALSE, result = "asis", fig.align="center", fig.width=11}
library(reshape2)
library(ggplot2)

plotParas = expand.grid(noiseStds, lambda)
names(plotParas) = c("noiseStd", "lambda")

for(i in (1:nrow(plotParas))){
  title = paste(paste(names(plotParas), plotParas[i,], sep=":"),collapse = ",")
  criterion = result["noiseStd"] == plotParas[i,"noiseStd"] & result["lambda"] == plotParas[i,"lambda"] & !is.na(result['extrapolateError']) & !is.na(result['inputError'])
  currentResult = result[criterion,]
  
  melted = melt(currentResult, c("freq", "amp"), measure.vars = c("extrapolateError", "inputError"))
  currentResult2 = dcast(melted, freq + amp ~ variable, mean, na.rm = TRUE)
  currentResult2[currentResult2["extrapolateError"] > 1, "extrapolateError"] = 1
  currentResult2[currentResult2["inputError"] > 1, "inputError"] = 1
  currentResult2[currentResult2["extrapolateError"] < 10^-10,"extrapolateError"] = 0
  currentResult2[currentResult2["inputError"] < 10^-10, "inputError"] = 0
  currentResult2$errorDiff = currentResult2$extrapolateError  - currentResult2$inputError
  currentResult2$errorDiffBool = as.numeric(currentResult2$extrapolateError  > currentResult2$inputError)
  melted2 = melt(currentResult2, c("freq", "amp"), measure.vars = c("extrapolateError", "inputError"))
  melted3 = melt(currentResult2, c("freq", "amp"), measure.vars = c("errorDiff"))
  melted4 = melt(currentResult2, c("freq", "amp"), measure.vars = c("errorDiffBool"))
  p = ggplot(melted2, aes(x=freq, y=amp)) + geom_tile(aes(fill=value)) + scale_fill_gradient(low = "white",high = "steelblue") + facet_grid(.~variable) + ggtitle(title)
  p2 = ggplot(melted3, aes(x=freq, y=amp)) + geom_tile(aes(fill=value)) + scale_fill_gradient(low = "white",high = "steelblue") + facet_grid(.~variable) + ggtitle(title)
  p3 = ggplot(melted4, aes(x=freq, y=amp)) + geom_tile(aes(fill=value)) + scale_fill_gradient(low = "white",high = "steelblue") + facet_grid(.~variable) + ggtitle(title)
  # knitr::kable(melted)
  print(p)
  print(p2)
  print(p3)
}
```

### Grid test result
```{r, echo=FALSE, result = "markup", warning=FALSE, message=FALSE}
knitr::kable(result)
write.csv(result, file = csvResultName, append = FALSE, quote = FALSE, sep = ",", row.names = FALSE, col.names = TRUE)
```
