ACTIGRAPH_HEADER_SR_PATTERN = "([0-9]+) Hz"
ACTIGRAPH_HEADER_FIRMWARE_PATTERN = "Firmware v([0-9]+.[0-9]+.[0-9]+)"
ACTIGRAPH_HEADER_SOFTWARE_PATTERN = "ActiLife v([0-9]+.[0-9]+.[0-9]+)"
ACTIGRAPH_HEADER_SERIALNUM_PATTERN = "Serial Number: ([A-Za-z0-9]+)"
ACTIGRAPH_TIMESTAMP = "%m/%d/%Y %H:%M:%OS"
ACTIGRAPH_IMU_TIMESTAMP = "%Y-%m-%dT%H:%M:%OS"

